# Generated by Django 6.0.4 on 2026-04-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificado_projeto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificado',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='url_imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
