# Generated by Django 6.0.4 on 2026-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_certificado_delete_projeto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoal',
            name='url_imagem',
            field=models.ImageField(default='', upload_to='perfil/'),
            preserve_default=False,
        ),
    ]
