# Generated by Django 6.0.4 on 2026-04-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pessoal_url_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoal',
            old_name='url_imagem',
            new_name='imagem',
        ),
    ]
