# Generated by Django 6.0.4 on 2026-05-18 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_url_imagem_pessoal_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoal',
            options={'verbose_name': 'Perfil Pessoal', 'verbose_name_plural': 'Perfis Pessoais'},
        ),
        migrations.RemoveField(
            model_name='pessoal',
            name='imagem',
        ),
        migrations.AddField(
            model_name='pessoal',
            name='url_imagem',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pessoal',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='curso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='git',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='linked',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
