# Generated by Django 6.0.4 on 2026-05-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pessoal_options_remove_pessoal_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoal',
            name='url_imagem',
        ),
        migrations.AddField(
            model_name='pessoal',
            name='imagem',
            field=models.ImageField(default='', upload_to='perfil/'),
            preserve_default=False,
        ),
    ]
