# Generated by Django 6.0.4 on 2026-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PESSOAL', 'Pessoal'), ('DISCIPLINA', 'Disciplina')], max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link_git', models.URLField()),
            ],
        ),
    ]
